version: "3.9"
services:
  python311:
    build:
      context: .
      dockerfile: Dockerfile
    image: raspios-lite-armhf-2022-04-04:python3.11.3
    container_name: raspios-lite-armhf
    platform: linux/arm/v7
    tty: true
    volumes:
      - .:/workspace
    working_dir: /workspace
