name: awscrt

on:
    pull_request:
    push:
        branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Import Docker Image
      run: bash import_docker_image.sh
    - name: Set up a Git safe directory
      run: git config --global --add safe.directory "${{ github.workspace }}/app"
    - name: Build awsiotsdk
      run: |
        docker run -i --name raspios-lite-armhf -v $PWD:/app -w /app --platform linux/arm/v7 raspios-lite-armhf:2022-04-04 bash << EOF
        bash build_awscrt.sh
        EOF
    - name: docker ps
      run: docker ps -a
    - name: cp wheel
      run: sudo docker cp raspios-lite-armhf:/app/aws-crt-python/dist /dist
    - name: remove docker container
      run: docker rm raspios-lite-armhf
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: /dist
