name: CI

on:
    pull_request:
    push:
        branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    - name: Pull Docker Image
      run: docker pull ghcr.io/okhiroyuki/raspios-lite-armhf:2022-04-04
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - run: |
        docker run --rm --entrypoint bin/bash ghcr.io/okhiroyuki/raspios-lite-armhf:2022-04-04 << EOF
        set -xeu
        uname -a
        apt update
        EOF
