name: CI

on:
    pull_request:
    push:
        branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    - name: Pull Docker Image
      run: docker pull ghcr.io/okhiroyuki/raspios-lite-armhf:2022-04-04
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Build awsiotsdk
      run: |
        docker run --rm -i -v $PWD:/app ghcr.io/okhiroyuki/raspios-lite-armhf:2022-04-04 bash << EOF
        set -xeu
        apt update
        apt install git -y
        git clone https://github.com/aws/aws-iot-device-sdk-python-v2.git
        cd aws-iot-device-sdk-python-v2
        python3 -m venv venv
        source venv/bin/activate
        python3 -m pip install --upgrade awscrt
        python setup.py bdist_wheel
        EOF
    - name: Check dist
      run: ls -l dist
