name: CI

on:
    pull_request:
    push:
        branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    - name: Pull Docker Image
      run: docker pull ghcr.io/okhiroyuki/raspios-lite-armhf:2022-04-04
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: mkdir dist
      run: mkdir dist
    - name: Build awsiotsdk
      run: |
        docker run -i -v $PWD:/app -w /app ghcr.io/okhiroyuki/raspios-lite-armhf:2022-04-04 bash << EOF
        set -xeu
        EOF
    - name: docker ps
      run: docker ps -a
    - name: cp wheel
      run: docker cp ghcr.io/okhiroyuki/raspios-lite-armhf:2022-04-04:/app/aws-iot-device-sdk-python-v2 /dist
    - name: remove docker container
      run: docker rm ghcr.io/okhiroyuki/raspios-lite-armhf:2022-04-04
    - name: Check dist
      run: ls -l dist
